name: Send mail

on: push

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: outlook.office365.com
          # Required mail server port:
          server_port: 993
          # Required mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Required mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: rafao1989@hotmail.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
  #        html_body: file://README.html
          # Optional carbon copy recipients:
  #        cc: kyloren@example.com,leia@example.com
